import React, {useState} from 'react';
import {
  View,
  TextInput,
  TouchableOpacity,
  Text,
  StyleSheet,
  Modal,
  FlatList,
} from 'react-native';

const demo = () => {
  const [modalVisible, setModalVisible] = useState(false);
  const [selectedCode, setSelectedCode] = useState('');

  // Manually create an array of country codes and calling codes
  const countryCodes = [
    {isSelect: false,calling_code: '+1'},
    {calling_code: '+1 340'},
    {calling_code: '+1 670'},
    {calling_code: '+1 671'},
    {calling_code: '+1 684'},
    {calling_code: '+1 787/939'},
    {calling_code: '+1 242'},
    {calling_code: '+1 246'},
    {calling_code: '+1 264'},
    {calling_code: '+1 268'},
    {calling_code: '+1 284'},
    {calling_code: '+1 345'},
    {calling_code: '+1 441'},
    {calling_code: '+1 473'},
    {calling_code: '+1 649'},
    {calling_code: '+1 664'},
    {calling_code: '+1 721'},
    {calling_code: '+1 758'},
    {calling_code: '+1 767'},
    {calling_code: '+1 784'},
    {calling_code: '+1 809 / 829 / 849'},
    {calling_code: '+1 868'},
    {calling_code: '+1 869'},
    {calling_code: '+1 876'},
    {calling_code: '+20'},
    {calling_code: '+210'},
    {calling_code: '+211'},
    {calling_code: '+212'},
    {calling_code: '+212 5288 / 5289'},
    {calling_code: '+213'},
    {calling_code: '+214'},
    {calling_code: '+215'},
    {calling_code: '+216'},
    {calling_code: '+217'},
    {calling_code: '+218'},
    {calling_code: '+219'},
    {calling_code: '+220'},
    {calling_code: '+221'},
    {calling_code: '+222'},
    {calling_code: '+223'},
    {calling_code: '+224'},
    {calling_code: '+225'},
    {calling_code: '+226'},
    {calling_code: '+227'},
    {calling_code: '+228'},
    {calling_code: '+229'},
    {calling_code: '+230'},
    {calling_code: '+231'},
    {calling_code: '+232'},
    {calling_code: '+233'},
    {calling_code: '+234'},
    {calling_code: '+235'},
    {calling_code: '+236'},
    {calling_code: '+237'},
    {calling_code: '+238'},
    {calling_code: '+239'},
    {calling_code: '+240'},
    {calling_code: '+241'},
    {calling_code: '+242'},
    {calling_code: '+243'},
    {calling_code: '+244'},
    {calling_code: '+245'},
    {calling_code: '+246'},
    {calling_code: '+247'},
    {calling_code: '+248'},
    {calling_code: '+249'},
    {calling_code: '+250'},
    {calling_code: '+251'},
    {calling_code: '+252'},
    {calling_code: '+253'},
    {calling_code: '+254'},
    {calling_code: '+255'},
    {calling_code: '+255 24'},
    {calling_code: '+256'},
    {calling_code: '+257'},
    {calling_code: '+258'},
    {calling_code: '+259'},
    {calling_code: '+260'},
    {calling_code: '+261'},
    {calling_code: '+262'},
    {calling_code: '+262 269 / 639'},
    {calling_code: '+263'},
    {calling_code: '+264'},
    {calling_code: '+265'},
    {calling_code: '+266'},
    {calling_code: '+267'},
    {calling_code: '+268'},
    {calling_code: '+269'},
    {calling_code: '+27'},
    {calling_code: '+28x'},
    {calling_code: '+290'},
    {calling_code: '+290 8'},
    {calling_code: '+291'},
    {calling_code: '+292'},
    {calling_code: '+293'},
    {calling_code: '+294'},
    {calling_code: '+295'},
    {calling_code: '+296'},
    {calling_code: '+297'},
    {calling_code: '+298'},
    {calling_code: '+299'},
    {calling_code: '+30'},
    {calling_code: '+31'},
    {calling_code: '+32'},
    {calling_code: '+33'},
    {calling_code: '+34'},
    {calling_code: '+350'},
    {calling_code: '+351'},
    {calling_code: '+352'},
    {calling_code: '+353'},
    {calling_code: '+354'},
    {calling_code: '+355'},
    {calling_code: '+356'},
    {calling_code: '+357'},
    {calling_code: '+358'},
    {calling_code: '+358 18'},
    {calling_code: '+359'},
    {calling_code: '+36'},
    {calling_code: '+37'},
    {calling_code: '+370'},
    {calling_code: '+371'},
    {calling_code: '+372'},
    {calling_code: '+373'},
    {calling_code: '+373 2 / 5'},
    {calling_code: '+374'},
    {calling_code: '+374 47 / 97'},
    {calling_code: '+375'},
    {calling_code: '+376'},
    {calling_code: '+377'},
    {calling_code: '+377 44 / 45'},
    {calling_code: '+378'},
    {calling_code: '+379'},
    {calling_code: '+38'},
    {calling_code: '+380'},
    {calling_code: '+381'},
    {calling_code: '+381 28 / 29 / 38 / 39'},
    {calling_code: '+382'},
    {calling_code: '+383'},
    {calling_code: '+384'},
    {calling_code: '+385'},
    {calling_code: '+386'},
    {calling_code: '+386 43 / 49'},
    {calling_code: '+387'},
    {calling_code: '+388'},
    {calling_code: '+389'},
    {calling_code: '+39'},
    {calling_code: '+39 06 698'},
    {calling_code: '+40'},
    {calling_code: '+41'},
    {calling_code: '+42'},
    {calling_code: '+420'},
    {calling_code: '+421'},
    {calling_code: '+422'},
    {calling_code: '+423'},
    {calling_code: '+424'},
    {calling_code: '+425'},
    {calling_code: '+426'},
    {calling_code: '+427'},
    {calling_code: '+428'},
    {calling_code: '+429'},
    {calling_code: '+43'},
    {calling_code: '+44'},
    {calling_code: '+44 1481'},
    {calling_code: '+44 1534'},
    {calling_code: '+44 1624'},
    {calling_code: '+45'},
    {calling_code: '+46'},
    {calling_code: '+47'},
    {calling_code: '+47 79'},
    {calling_code: '+47 79'},
    {calling_code: '+48'},
    {calling_code: '+49'},
    {calling_code: '+500'},
    {calling_code: '+500 x'},
    {calling_code: '+501'},
    {calling_code: '+502'},
    {calling_code: '+503'},
    {calling_code: '+504'},
    {calling_code: '+505'},
    {calling_code: '+506'},
    {calling_code: '+507'},
    {calling_code: '+508'},
    {calling_code: '+509'},
    {calling_code: '+51'},
    {calling_code: '+52'},
    {calling_code: '+53'},
    {calling_code: '+54'},
    {calling_code: '+55'},
    {calling_code: '+56'},
    {calling_code: '+56 32'},
    {calling_code: '+57'},
    {calling_code: '+58'},
    {calling_code: '+590'},
    {calling_code: '+591'},
    {calling_code: '+592'},
    {calling_code: '+593'},
    {calling_code: '+594'},
    {calling_code: '+595'},
    {calling_code: '+596'},
    {calling_code: '+597'},
    {calling_code: '+598'},
    {calling_code: '+599'},
    {calling_code: '+599 3'},
    {calling_code: '+599 4'},
    {calling_code: '+599 5'},
    {calling_code: '+599 7'},
    {calling_code: '+599 9'},
    {calling_code: '+60'},
    {calling_code: '+61'},
    {calling_code: '+61 8 9162'},
    {calling_code: '+61 8 9164'},
    {calling_code: '+62'},
    {calling_code: '+63'},
    {calling_code: '+64'},
    {calling_code: '+64 xx'},
    {calling_code: '+65'},
    {calling_code: '+66'},
    {calling_code: '+670'},
    {calling_code: '+671'},
    {calling_code: '+672'},
    {calling_code: '+672 1x'},
    {calling_code: '+672 3'},
    {calling_code: '+673'},
    {calling_code: '+674'},
    {calling_code: '+675'},
    {calling_code: '+676'},
    {calling_code: '+677'},
    {calling_code: '+678'},
    {calling_code: '+679'},
    {calling_code: '+680'},
    {calling_code: '+681'},
    {calling_code: '+682'},
    {calling_code: '+683'},
    {calling_code: '+684'},
    {calling_code: '+685'},
    {calling_code: '+686'},
    {calling_code: '+687'},
    {calling_code: '+688'},
    {calling_code: '+689'},
    {calling_code: '+690'},
    {calling_code: '+691'},
    {calling_code: '+692'},
    {calling_code: '+693'},
    {calling_code: '+694'},
    {calling_code: '+695'},
    {calling_code: '+696'},
    {calling_code: '+697'},
    {calling_code: '+698'},
    {calling_code: '+699'},
    {calling_code: '+7'},
    {calling_code: '+7 6xx / 7xx'},
    {calling_code: '+7 840 / 940'},
    {calling_code: '+800'},
    {calling_code: '+801'},
    {calling_code: '+802'},
    {calling_code: '+803'},
    {calling_code: '+804'},
    {calling_code: '+805'},
    {calling_code: '+806'},
    {calling_code: '+807'},
    {calling_code: '+808'},
    {calling_code: '+809'},
    {calling_code: '+81'},
    {calling_code: '+82'},
    {calling_code: '+83x'},
    {calling_code: '+84'},
    {calling_code: '+850'},
    {calling_code: '+851'},
    {calling_code: '+852'},
    {calling_code: '+853'},
    {calling_code: '+854'},
    {calling_code: '+855'},
    {calling_code: '+856'},
    {calling_code: '+857'},
    {calling_code: '+858'},
    {calling_code: '+859'},
    {calling_code: '+86'},
    {calling_code: '+870'},
    {calling_code: '+871'},
    {calling_code: '+872'},
    {calling_code: '+873'},
    {calling_code: '+874'},
    {calling_code: '+875'},
    {calling_code: '+876'},
    {calling_code: '+877'},
    {calling_code: '+878'},
    {calling_code: '+879'},
    {calling_code: '+880'},
    {calling_code: '+881'},
    {calling_code: '+882'},
    {calling_code: '+883'},
    {calling_code: '+884'},
    {calling_code: '+885'},
    {calling_code: '+886'},
    {calling_code: '+887'},
    {calling_code: '+888'},
    {calling_code: '+889'},
    {calling_code: '+89x'},
    {calling_code: '+90'},
    {calling_code: '+90 392'},
    {calling_code: '+91'},
    {calling_code: '+92'},
    {calling_code: '+93'},
    {calling_code: '+94'},
    {calling_code: '+95'},
    {calling_code: '+960'},
    {calling_code: '+961'},
    {calling_code: '+962'},
    {calling_code: '+963'},
    {calling_code: '+964'},
    {calling_code: '+965'},
    {calling_code: '+966'},
    {calling_code: '+967'},
    {calling_code: '+968'},
    {calling_code: '+969'},
    {calling_code: '+970'},
    {calling_code: '+971'},
    {calling_code: '+972'},
    {calling_code: '+973'},
    {calling_code: '+974'},
    {calling_code: '+975'},
    {calling_code: '+976'},
    {calling_code: '+977'},
    {calling_code: '+978'},
    {calling_code: '+979'},
    {calling_code: '+98'},
    {calling_code: '+990'},
    {calling_code: '+991'},
    {calling_code: '+992'},
    {calling_code: '+993'},
    {calling_code: '+994'},
    {calling_code: '+995'},
    {calling_code: '+995 44'},
    {calling_code: '+995 xx'},
    {calling_code: '+996'},
    {calling_code: '+997'},
    {calling_code: '+998'},
    {calling_code: '+999'},
  ];
  const handleCodeSelection = code => {
    setSelectedCode(code);
    setModalVisible(false);
  };
  return (
    <View style={styles.screenContainer}>
      <TouchableOpacity
        onPress={() => setModalVisible(true)}
        style={{
          borderWidth: 1,
          borderColor: '#000',
          padding: 10,
          flexDirection: 'row',
          justifyContent: 'space-between',
          alignItems: 'center',
        }}>
        <TextInput
          value={selectedCode}
          placeholder='Code'
          placeholderTextColor={'#251E1F'}
          onChangeText={text => setSelectedCode(text)}
          editable={false} // Disable manual editing of the TextInput
          style={{color: selectedCode ? '#323237' : '#929094',fontSize:16}}
        />
        <Text>▼</Text>
      </TouchableOpacity>
      <Modal
        animationType="slide"
        transparent={true}
        visible={modalVisible}
        onRequestClose={() => setModalVisible(false)}>
        <View
          style={{
            flex: 1,
            backgroundColor: 'rgba(0, 0, 0, 0.5)',
          }}>
            <TouchableOpacity onPress={() => setModalVisible(false)} style={{flex: 0.4}}></TouchableOpacity>
          <View
            style={{
              backgroundColor: '#fff',
              padding: 20,
              borderRadius: 10,
              flexGrow: 1,
              flex:0.6
            }}>
            <FlatList
              data={countryCodes}
              renderItem={({item}) => (
                <TouchableOpacity
                style={{borderBottomColor:'#251E1F',borderBottomWidth:0.5}}
                  onPress={() => handleCodeSelection(item.calling_code)}>
                  <Text style={{color:'#251E1F',fontSize:18}}>{item.calling_code}</Text>
                </TouchableOpacity>
              )}
              keyExtractor={(item, index) => index.toString()}
            />
          </View>
        </View>
      </Modal>
    </View>
  );
};

const styles = StyleSheet.create({
  screenContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  input: {
    borderWidth: 1,
    borderColor: '#ccc',
    padding: 10,
    width: 200,
    marginBottom: 10,
  },
  downArrow: {
    marginLeft: -30, // Adjust as per your preference
  },
});

export default demo;
